### ISSUE TITLE
Error al abrir el primer programa

### ISSUE THREAD

**Issue by adriana-salgueiro** [dfloreaa/Apuntes-IIC2613#1]
Hola! Estoy teniendo un problema al correr el primer programa. Quería saber si debo enlazar vscode y clingo, o quizá el problema es la ubicación del archivo del programa, estoy poniéndolo en la misma ubicación que la carpeta "Examples" de clingo. Mi error en terminal es el siguiente:

clingo version 5.4.0
Reading from primer_programa.lp
<cmd>: error: file could not be opened:
  primer_programa.lp

*** ERROR: (clingo): parsing failed
UNKNOWN

Models       : 0+
Calls        : 1
Time         : 0.008s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.000s

Estaré atenta a la respuesta, gracias :)

**Comment by dfloreaa** [comment]
Hola, estas copiando el programa desde el repositorio o el texto desde el pdf?
Me imagino que podria haber un error de formato al copiar el texto desde el pdf

Saludos ☺️

**Comment by adriana-salgueiro** [comment]
Hola, Daniel. Ya lo solucioné, muchas gracias!
